// packages/vue2/src/components/tag/Tag.vue
<template>
  <span>
    <template v-if="closeTag && iconName">
      <button
        v-show="open"
        :class="[buttonClass, skinClass, sizeClass, textStyleClass]"
        :type="type"
        role="button"
        :aria-label="ariaLabel"
        @keyup.enter="close"
        @click="close"
      >
        <pkt-icon class="pkt-tag__icon" :name="iconName"></pkt-icon>
        <slot></slot>
        <pkt-icon class="pkt-tag__close-btn" name="close"></pkt-icon>
      </button>
    </template>

    <template v-else-if="closeTag">
      <button
        v-show="open"
        :class="[buttonClass, skinClass, sizeClass, textStyleClass]"
        :type="type"
        role="button"
        :aria-label="ariaLabel"
        @keyup.enter="close"
        @click="close"
      >
        <pkt-icon class="pkt-tag__close-btn" name="close"></pkt-icon>
        <slot></slot>
      </button>
    </template>

    <template v-else-if="iconName">
      <span class="pkt-tag" :class="[skinClass, sizeClass, textStyleClass]"
        ><pkt-icon class="pkt-tag__icon" :name="iconName"></pkt-icon>
        <slot></slot>
      </span>
    </template>

    <template v-else>
      <span class="pkt-tag" :class="[skinClass, sizeClass, textStyleClass]">
        <slot></slot>
      </span>
    </template>
  </span>
</template>
<script>
import PktIcon from '../icon/Icon.vue';

export default {
  name: 'PktTag',
  components: { PktIcon },
  props: {
    skin: {
      type: String,
      default: 'blue',
      validator(value) {
        return ['blue', 'green', 'red', 'beige', 'yellow', 'grey', 'blue-light'].includes(value);
      },
    },
    textStyle: {
      type: String,
      default: 'normal',
      validator(value) {
        return ['thin-text', 'normal-text'].includes(value);
      },
    },
    size: {
      type: String,
      default: 'medium',
      validator(value) {
        return ['small', 'medium', 'large'].includes(value);
      },
    },
    closeTag: {
      type: Boolean,
      default: false,
    },
    iconName: {
      type: String,
      default: '',
    },
    type: {
      type: String,
      default: 'button',
      validator: (value) => ['button', 'submit', 'reset'].includes(value),
    },
    ariaLabel: {
      type: String,
      default: 'close',
    },
  },
  data: () => ({
    closed: false,
  }),
  methods: {
    close() {
      this.closed = true;
      this.$emit('on-close', this.closed);
    },
  },
  computed: {
    skinClass() {
      return [`pkt-tag--${this.skin}`];
    },
    sizeClass() {
      return [`pkt-tag--${this.size}`];
    },
    textStyleClass() {
      return [`pkt-tag--${this.textStyle}`];
    },
    buttonClass() {
      return [
        'pkt-tag',
        'pkt-btn',
        'pkt-btn--tertiary',
        {
          'pkt-btn--icons-right-and-left': this.iconName && this.closeTag,
          'pkt-btn--icon-right': this.closeTag && !this.iconName,
        },
      ];
    },
    open() {
      return !this.closed;
    },
  },
};
</script>

// packages/react/src/components/tag/Tag.tsx
import React, { ForwardedRef, forwardRef, useState } from 'react';

import { PktIcon } from '../icon/Icon'

export interface IPktTag extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  skin?: 'blue' | 'green' | 'red' | 'beige' | 'yellow' | 'grey' | 'blue-light';
  textStyle?: 'normal-text' | 'thin-text';
  size?: 'small' | 'medium' | 'large';
  closeTag?: boolean;
  iconName?: string;
  ariaLabel?: string;
}

export const PktTag = forwardRef(({
  children,
  className,
  skin = 'blue',
  textStyle = 'normal-text',
  size = 'medium',
  closeTag = false,
  iconName = '',
  type = 'button',
  ariaLabel = 'close',
  onClick = () => { },
}: IPktTag, ref: ForwardedRef<HTMLButtonElement>) => {
  const [closed, setClosed] = useState(false);

  const close = (event: React.MouseEvent<HTMLButtonElement>) => {
    setClosed(true);
    onClick(event);
  };

  const classes = [
    'pkt-tag',
    size && `pkt-tag--${size}`,
    skin && `pkt-tag--${skin}`,
    textStyle && `pkt-tag--${textStyle}`,
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const buttonClass = [
    'pkt-tag',
    'pkt-btn',
    'pkt-btn--tertiary',
    size && `pkt-tag--${size}`,
    skin && `pkt-tag--${skin}`,
    textStyle && `pkt-tag--${textStyle}`,
    iconName && closeTag ? 'pkt-btn--icons-right-and-left' : null,
    closeTag && !iconName ? 'pkt-btn--icon-right' : null,
    className,
  ]
    .filter(Boolean)
    .join(' ');


  const open = !closed;

  if (closeTag && iconName) {
    return (
      <>
        {open && (
          <button
            className={buttonClass}
            type={type}
            aria-label={ariaLabel}
            onClick={close}
            ref={ref}
          >
            <PktIcon className="pkt-tag__icon" name={iconName}></PktIcon>
            {children}
            <PktIcon className="pkt-tag__close-btn" name="close"></PktIcon>
          </button>
        )}
      </>
    );
  } else if (closeTag) {
    return (
      <>
        {open && (
          <button
            className={buttonClass}
            type={type}
            aria-label={ariaLabel}
            onClick={close}
            ref={ref}
          >
            <PktIcon className="pkt-tag__close-btn" name="close"></PktIcon>
            {children}
          </button>
        )}
      </>
    );
  } else if (iconName) {
    return (
      <span className={classes}>
        <PktIcon className="pkt-tag__icon" name={iconName}></PktIcon>
        {children}
      </span>
    );
  } else {
    return (
      <span className={classes}>
        {children}
      </span>
    );
  }
});

PktTag.displayName = 'PktTag'
