// packages/react/src/components/radio/RadioButton.tsx
import React, { ForwardedRef, forwardRef } from 'react'

export interface IRadio extends React.InputHTMLAttributes<HTMLInputElement> {
  id: string;
  name: string;
  label: string;
  hasTile?: boolean;
  disabled?: boolean;
  checkHelptext?: string;
  hasError?: boolean;
  value?: string;
}

export const PktRadioButton = forwardRef(
  ({
    id,
    name,
    label,
    className,
    hasTile = false,
    disabled = false,
    checkHelptext,
    hasError = false,
    ...props }: IRadio,
    ref: ForwardedRef<HTMLInputElement>): React.ReactElement => {

    // Define the classes
    const classes = [
      className,
      'pkt-input-check',
    ].filter(Boolean)
      .join(' ')

    return (

      <div className={classes}>
        <div className={`pkt-input-check__input ${hasTile ? 'pkt-input-check__input--tile' : ''} ${disabled && hasTile ? 'pkt-input-check__input--tile-disabled' : ''}`}>
          <input
            ref={ref}
            className={`pkt-input-check__input-checkbox ${hasError ? 'pkt-input-check__input-checkbox--error' : ''}`}
            type="radio"
            id={id}
            disabled={disabled}
            name={name}
            {...props}
          />
          <label className="pkt-input-check__input-label" htmlFor={id}>
            {label}
            {checkHelptext && (
              <div className="pkt-input-check__input-helptext">
                {checkHelptext}
              </div>
            )}
          </label>
        </div>
      </div>
    )
  },
)

PktRadioButton.displayName = 'PktRadioButton'

// packages/vue/src/components/radiobutton/Radiobutton.vue
<template>
  <div class="pkt-input-check">
    <div :class="[{ 'pkt-input-check__input--tile': hasTile }, 'pkt-input-check__input']">
      <input
        class="pkt-input-check__input-checkbox"
        :class="{ 'pkt-input-check__input-checkbox--error': hasError }"
        type="radio"
        v-bind="$attrs"
        :id="id"
        :name="name"
        :value="label"
        :checked="label === modelValue"
        @change="handleChange"
        :disabled="disabled"
      />
      <label class="pkt-input-check__input-label" :for="id">
        {{ label }}
        <div v-if="checkHelptext" class="pkt-input-check__input-helptext">
          {{ checkHelptext }}
        </div>
      </label>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PktRadioButton',
  props: {
    id: {
      type: String,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      required: true,
    },
    modelValue: {
      type: String,
      required: false,
      default: '',
    },
    hasTile: {
      type: Boolean,
      required: false,
      default: false,
    },
    disabled: {
      type: Boolean,
      required: false,
      default: false,
    },
    checkHelptext: {
      type: String,
      required: false,
    },
    hasError: {
      type: Boolean,
      required: false,
      default: false,
    },
  },
  emits: ['update:modelValue', 'onChange'],
  methods: {
    handleChange() {
      this.$emit('update:modelValue', this.label)
      this.$emit('onChange', this.label)
    },
  },
}
</script>
