// packages/react/src/components/textinput/Textinput.tsx
import React, { ForwardedRef, forwardRef, InputHTMLAttributes } from 'react'

import { PktIcon } from '../icon/Icon'
import { PktInputWrapper } from '../inputwrapper/InputWrapper'

export interface IPktTextinput extends InputHTMLAttributes<HTMLInputElement> {
  id: string
  ariaDescribedby?: string
  ariaLabelledby?: string
  autocomplete?: string
  disabled?: boolean
  errorMessage?: string
  hasError?: boolean
  helptext?: string
  helptextDropdown?: string
  helptextDropdownButton?: string
  iconNameRight?: string
  inline?: boolean
  fullwidth?: boolean
  label: string
  name?: string
  optionalTag?: boolean
  optionalText?: string
  requiredTag?: boolean
  requiredText?: string
  placeholder?: string
  prefix?: string
  suffix?: string
  type?: string
  useWrapper?: boolean
  value?: string
  omitSearchIcon?: boolean
}

export const PktTextinput = forwardRef(
  (
    {
      id,
      ariaDescribedby,
      ariaLabelledby,
      autocomplete = 'off',
      className,
      disabled = false,
      errorMessage,
      hasError = false,
      helptext,
      helptextDropdown,
      helptextDropdownButton,
      iconNameRight,
      inline = false,
      fullwidth = false,
      label,
      name,
      optionalTag = false,
      optionalText,
      requiredTag = false,
      requiredText,
      placeholder,
      prefix,
      suffix,
      type = 'text',
      useWrapper = true,
      omitSearchIcon = false,
      value,
      ...props
    }: IPktTextinput,
    ref: ForwardedRef<HTMLInputElement>,
  ) => {
    const classNames = [className, 'pkt-textinput'].join(' ')
    const labelledBy = ariaLabelledby || `${id}-label`
    const shouldShowSearchIcon = type === 'search' && !iconNameRight && !omitSearchIcon
    return (
      <PktInputWrapper
        ariaDescribedby={ariaDescribedby}
        className={classNames}
        disabled={disabled}
        errorMessage={errorMessage}
        forId={id}
        hasError={hasError}
        helptext={helptext}
        helptextDropdown={helptextDropdown}
        helptextDropdownButton={helptextDropdownButton}
        inline={inline}
        label={label}
        optionalTag={optionalTag}
        optionalText={optionalText}
        requiredTag={requiredTag}
        requiredText={requiredText}
        useWrapper={useWrapper}
      >
        <div className="pkt-input__container">
          {prefix && <div className="pkt-input-prefix">{prefix}</div>}
          <input
            ref={ref}
            className={`pkt-input ${fullwidth ? 'pkt-input--fullwidth' : ''}`}
            type={type}
            name={name || id}
            id={id}
            placeholder={placeholder}
            autoComplete={autocomplete}
            value={value}
            disabled={disabled}
            aria-invalid={hasError}
            aria-errormessage={`${id}-error`}
            aria-labelledby={labelledBy}
            {...props}
          />
          {suffix && (
            <p className="pkt-input-suffix">
              {suffix}
              {iconNameRight && <PktIcon className="pkt-input-suffix-icon" name={iconNameRight} />}
              {shouldShowSearchIcon && (
                <PktIcon className="pkt-input-suffix-icon" name="magnifying-glass-big" />
              )}
            </p>
          )}

          {!suffix && iconNameRight && <PktIcon className="pkt-input-icon" name={iconNameRight} />}
          {!suffix && shouldShowSearchIcon && (
            <PktIcon className="pkt-input-icon" name="magnifying-glass-big" />
          )}
        </div>
      </PktInputWrapper>
    )
  },
)

// packages/vue2/src/components/textinput/Textinput.vue
<template>
  <PktInputWrapper
    class="pkt-textinput"
    :forId="id"
    :label="label"
    :helptext="helptext"
    :helptextDropdown="helptextDropdown"
    :helptextDropdownButton="helptextDropdownButton"
    :optionalTag="optionalTag"
    :optionalText="optionalText"
    :requiredTag="requiredTag"
    :requiredText="requiredText"
    :hasError="hasError"
    :errorMessage="errorMessage"
    :disabled="disabled"
    :inline="inline"
    :ariaDescribedby="ariaDescribedby"
    :useWrapper="useWrapper"
    @toggleHelpText="$emit('toggleHelpText')"
  >
    <div class="pkt-input__container">
      <div v-if="prefix" class="pkt-input-prefix">{{ prefix }}</div>
      <input
        v-bind="$attrs"
        v-on="{
          ...$listeners,
          input: (event) => $emit('input', event.target.value),
        }"
        :class="{
          'pkt-input': true,
          'pkt-input--fullwidth': fullwidth,
        }"
        :type="type"
        :name="name || id"
        :id="id"
        :placeholder="placeholder"
        :autocomplete="autocomplete"
        :value="value"
        :disabled="disabled"
        :aria-invalid="hasError"
        :aria-errormessage="hasError ? `${id}-error` : ''"
        :aria-labelledby="labelledBy"
        ref="input"
      />
      <p v-if="suffix" class="pkt-input-suffix">
        {{ suffix }}
        <pkt-icon v-if="iconNameRight" class="pkt-input-suffix-icon" :name="iconNameRight" />
        <pkt-icon v-else-if="shouldShowSearchIcon" class="pkt-input-suffix-icon" name="magnifying-glass-big" />
      </p>
      <pkt-icon v-else-if="iconNameRight" class="pkt-input-icon" :name="iconNameRight" />
      <pkt-icon v-else-if="shouldShowSearchIcon" class="pkt-input-icon" name="magnifying-glass-big" />
    </div>
  </PktInputWrapper>
</template>

<script>
import PktIcon from '../icon/Icon.vue'
import PktAlert from '../alert/Alert.vue'
import PktInputWrapper from '../inputwrapper/InputWrapper.vue'

export default {
  name: 'PktTextinput',
  components: { PktIcon, PktAlert, PktInputWrapper },
  inheritAttrs: false,
  props: {
    label: {
      type: String,
      required: true,
      default: 'input',
    },
    helptext: {
      type: String,
      required: false,
    },
    helptextDropdown: {
      type: String,
      required: false,
    },
    helptextDropdownButton: {
      type: String,
      required: false,
    },
    optionalTag: {
      type: Boolean,
      required: false,
      default: false,
    },
    optionalText: {
      type: String,
      required: false,
    },
    requiredTag: {
      type: Boolean,
      required: false,
      default: false,
    },
    requiredText: {
      type: String,
      required: false,
    },
    hasError: {
      type: Boolean,
      required: false,
    },
    errorMessage: {
      type: String,
      required: false,
    },
    name: {
      type: String,
      required: false,
    },
    id: {
      type: String,
      required: true,
    },
    placeholder: {
      type: String,
      required: false,
    },
    type: {
      type: String,
      required: false,
      default: 'text',
    },
    autocomplete: {
      type: String,
      required: false,
      default: 'off',
    },
    value: {
      type: String,
      required: false,
    },
    suffix: {
      type: String,
      required: false,
    },
    prefix: {
      type: String,
      required: false,
    },
    iconNameRight: {
      type: String,
      required: false,
    },
    disabled: {
      type: Boolean,
      required: false,
      default: false,
    },
    inline: {
      type: Boolean,
      required: false,
      default: false,
    },
    fullwidth: {
      type: Boolean,
      default: false,
    },
    ariaLabelledby: {
      type: String,
      required: false,
    },
    ariaDescribedby: {
      type: String,
      required: false,
    },
    useWrapper: {
      type: Boolean,
      default: true,
    },
    omitSearchIcon: {
      type: Boolean,
      default: false,
    },
  },
  computed: {
    labelledBy() {
      this.ariaLabelledby || `${this.id}-label`
    },
    shouldShowSearchIcon() {
      return this.type === 'search' && !this.iconNameRight && !this.omitSearchIcon
    },
  },
}
</script>
