// packages/vue2/src/views/Linkcard.vue
<template>
  <page-main class="pkt-container">
    <h1>Linkcard</h1>

    <section class="component">
      <div class="component__block-example">
        <h2>Linkcard default</h2>
        <pkt-linkcard href="" title="Overskrift her" iconName="user"
          >Tekst som går over flere linjer og som forklarer innholdet på den siden man kommer.</pkt-linkcard
        >
        <h2>Linkcard blue</h2>
        <pkt-linkcard href="" title="Overskrift her" iconName="user" skin="blue"
          >Tekst som går over flere linjer og som forklarer innholdet på den siden man kommer.</pkt-linkcard
        >
        <h2>Linkcard beige</h2>
        <pkt-linkcard href="" title="Overskrift her" iconName="chevron-right" skin="beige"
          >Tekst som går over flere linjer og som forklarer innholdet på den siden man kommer.</pkt-linkcard
        >
        <h2>Linkcard beige-outline</h2>
        <pkt-linkcard href="#" title="Overskrift her" iconName="user" skin="beige-outline"
          >Tekst som går over flere linjer og som forklarer innholdet på den siden man kommer.</pkt-linkcard
        >
        <h2>Linkcard grey-outline</h2>
        <pkt-linkcard href="#" title="Overskrift her" iconName="user" skin="grey-outline"
          >Tekst som går over flere linjer og som forklarer innholdet på den siden man kommer.</pkt-linkcard
        >
        <pkt-linkcard href="www.example.com" title="Åpne i ny fane" iconName="user" openInNewTab external
          >Tekst som går over flere linjer og som forklarer innholdet på den siden man kommer.</pkt-linkcard
        >
      </div>
    </section>
  </page-main>
</template>

<script>
import { PktLinkcard } from '@/components/linkcard';
import PageMain from '@/dev-components/PageMain.vue';

export default {
  name: 'Linkcard',
  components: {
    PktLinkcard,
    PageMain,
  },
};
</script>

// packages/react/src/routes/linkcard.tsx
import LinkCardSpec from 'componentSpecs/linkcard.json'
import React, { useState } from 'react'

import { IPktLinkCard } from '@/components/linkcard/LinkCard'
import ILinkCardSpec from '@/interfaces/ILinkCardSpec'

import { PktLinkCard } from '..'

export default function LinkCard() {
  const linkcardSpec = LinkCardSpec as ILinkCardSpec
  const [specProps] = useState(linkcardSpec.props)

  return (
    <main className="page-main pkt-container">
      <h1>Linkcard</h1>
      {specProps.skin.map((skinType: IPktLinkCard['skin'], index: number) => (
        <section className="component" key={`skin-${index}`}>
          <h2>Skin: {skinType}</h2>
          <div>
            <PktLinkCard title={skinType} key={`skin-${index}-${skinType}`} skin={skinType} >
              Skriv en informerende tekst om ønskelig tema her. Legg til knapper eller bilder om du
              ønsker
            </PktLinkCard>
          </div>
        </section>
      ))}
      <PktLinkCard title="Åpne link i ny fane" key="openInNewTab" href="https://www.example.com" openInNewTab external>
        Skriv en informerende tekst om ønskelig tema her. Legg til knapper eller bilder om du
        ønsker
      </PktLinkCard>
    </main>
  )
}
