// packages/vue2/src/views/Messagebox.vue
<template>
  <page-main class="pkt-container">
    <h1>Messagebox</h1>

    <section class="component">
      <h2>Standard versjon</h2>
      <div class="component__block-example">
        <pkt-messagebox title="Messagebox beige">
          Skriv en informerende tekst om ønskelig tema her. Legg til knapper eller bilder om du ønsker
          <ul>
            <li>Listeelement 1</li>
            <li>Listeelement 2</li>
            <li>Listeelement 3</li>
          </ul>
        </pkt-messagebox>
        <pkt-messagebox skin="red" title="Messagebox red">
          Skriv en informerende tekst om ønskelig tema her. Legg til knapper eller bilder om du ønsker
          <ul>
            <li>Listeelement 1</li>
            <li>Listeelement 2</li>
            <li>Listeelement 3</li>
          </ul></pkt-messagebox
        >

        <pkt-messagebox skin="blue" title="Messagebox blue">
          Skriv en informerende tekst om ønskelig tema her. Legg til knapper eller bilder om du ønsker
          <ul>
            <li>Listeelement 1</li>
            <li>Listeelement 2</li>
            <li>Listeelement 3</li>
          </ul></pkt-messagebox
        >

        <pkt-messagebox skin="green" title="Messagebox green">
          Skriv en informerende tekst om ønskelig tema her. Legg til knapper eller bilder om du ønsker
          <ul>
            <li>Listeelement 1</li>
            <li>Listeelement 2</li>
            <li>Listeelement 3</li>
          </ul></pkt-messagebox
        >
      </div>
    </section>

    <section class="component">
      <h2>Kompakt versjon</h2>
      <div class="component__block-example">
        <pkt-messagebox title="Messagebox beige" compact>
          Skriv en informerende tekst om ønskelig tema her. Legg til knapper eller bilder om du ønsker
          <ul>
            <li>Listeelement 1</li>
            <li>Listeelement 2</li>
            <li>Listeelement 3</li>
          </ul>
        </pkt-messagebox>
        <pkt-messagebox skin="red" title="Messagebox red" compact>
          Skriv en informerende tekst om ønskelig tema her. Legg til knapper eller bilder om du ønsker
          <ul>
            <li>Listeelement 1</li>
            <li>Listeelement 2</li>
            <li>Listeelement 3</li>
          </ul></pkt-messagebox
        >

        <pkt-messagebox skin="blue" title="Messagebox blue" compact>
          Skriv en informerende tekst om ønskelig tema her. Legg til knapper eller bilder om du ønsker
          <ul>
            <li>Listeelement 1</li>
            <li>Listeelement 2</li>
            <li>Listeelement 3</li>
          </ul></pkt-messagebox
        >

        <pkt-messagebox skin="green" title="Messagebox green" compact>
          Skriv en informerende tekst om ønskelig tema her. Legg til knapper eller bilder om du ønsker
          <ul>
            <li>Listeelement 1</li>
            <li>Listeelement 2</li>
            <li>Listeelement 3</li>
          </ul></pkt-messagebox
        >
      </div>
    </section>
  </page-main>
</template>

<script>
import spec from 'componentSpecs/messagebox.json'
import { PktMessagebox } from '@/components/messagebox'
import PageMain from '@/dev-components/PageMain.vue'

export default {
  name: 'Messagebox',
  data: () => ({
    specProps: spec.props,
  }),
  components: {
    PktMessagebox,
    PageMain,
  },
}
</script>

<style lang="scss"></style>

// packages/react/src/routes/messagebox.tsx
import MessageboxSpec from 'componentSpecs/messagebox.json'
import React, { useState } from 'react'

import { IPktMessagebox } from '@/components/messagebox/Messagebox'
import IMessageboxSpec from '@/interfaces/IMessageboxSpec'

import { PktMessagebox } from '..'

export default function Messagebox() {
  const messageboxSpec = MessageboxSpec as IMessageboxSpec
  const [specProps] = useState(messageboxSpec.props)

  return (
    <main className="page-main pkt-container">
      <h1>Messagebox</h1>
      <section className="component" key="standard">
        <h2>Standard</h2>
        {specProps.skin.map((skinType: IPktMessagebox['skin'], index: number) => (
          <>
            <div>
              <PktMessagebox title={skinType} key={`skin-${index}-${skinType}`} skin={skinType}>
                Skriv en informerende tekst om ønskelig tema her. Legg til knapper eller bilder om
                du ønsker
                <ul>
                  <li>Listeelement 1</li>
                  <li>Listeelement 2</li>
                  <li>Listeelement 3</li>
                </ul>
              </PktMessagebox>
              <br />
            </div>
          </>
        ))}
      </section>
      <section className="component" key="kompakt">
        <h2>Kompakt</h2>
        {specProps.skin.map((skinType: IPktMessagebox['skin'], index: number) => (
          <>
            <div>
              <PktMessagebox
                title={skinType}
                key={`skin-${index}-${skinType}`}
                skin={skinType}
                compact
              >
                Skriv en informerende tekst om ønskelig tema her. Legg til knapper eller bilder om
                du ønsker
                <ul>
                  <li>Listeelement 1</li>
                  <li>Listeelement 2</li>
                  <li>Listeelement 3</li>
                </ul>
              </PktMessagebox>
              <br />
            </div>
          </>
        ))}
      </section>
    </main>
  )
}
