// packages/vue/src/views/Switch.vue
<template>
  <page-main class="pkt-container">
    <h1>Switch</h1>

    <section class="component">
      <PktCheckbox isSwitch id="singleSwitch" label="Switch" v-model="singleSwitchValue" />
      <p>Med <code>labelPosition</code> kan man legge label til venstre:</p>
      <PktCheckbox isSwitch id="singleSwitch2" label="Switch" labelPosition="left" v-model="singleSwitchValue" />
      <p>Switch kan også presenteres med en skjult label:</p>
      <PktCheckbox isSwitch hideLabel id="singleSwitch3" label="Switch" v-model="singleSwitchValue" />
      <p>Single switch value: {{ singleSwitchValue }}</p>
    </section>

    <section class="component">
      <PktCheckbox
        isSwitch
        id="switchWithHelptext"
        label="Switch med hjelpetekst"
        checkHelptext="Denne valgfrie teksten kan brukes til å beskrive etiketten mer detaljert."
        @onChange="handleCustomChange"
      />
    </section>

    <section class="component">
      <PktCheckbox
        isSwitch
        id="switchWithHelptext2"
        label="Switch med hjelpetekst"
        checkHelptext="Denne valgfrie teksten kan brukes til å beskrive etiketten mer detaljert."
        labelPosition="left"
        @onChange="handleCustomChange"
      />
    </section>

    <section class="component">
      <PktCheckbox
        isSwitch
        id="switchWithDefaultChecked"
        label="Switch med default checked og disabled"
        disabled
        defaultChecked
      />
    </section>
    <section class="component">
      <PktCheckbox
        isSwitch
        id="switchWithDefaultChecked2"
        label="Switch med default checked og disabled"
        disabled
        hasTile
        defaultChecked
      />
    </section>

    <section class="component">
      <PktCheckbox isSwitch id="switchWithTile" label="Switch med tile" hasTile />
    </section>

    <section class="component">
      <h2>Med inputwrapper</h2>
      <pkt-input-wrapper
        label="Etikett"
        helptext="Dette er tekst over avmerkingsboksene."
        optionalTag
        optionalText="Valgfritt"
        forId="switchGroup3"
        hasFieldset
      >
        <PktCheckbox
          isSwitch
          v-for="(item, index) in switchGroup"
          :key="index"
          :id="item.id"
          :label="item.label"
          v-model="item.checked"
          @change="handleChange(item.id)"
          :hasTile="false"
          :checkHelptext="item.checkHelptext"
        >
        </PktCheckbox>
      </pkt-input-wrapper>

      <p>Group Switch Values:</p>
      <ul>
        <li v-for="(item, index) in switchGroup" :key="index">{{ item.label }}: {{ item.checked }}</li>
      </ul>
    </section>

    <section class="component">
      <h2>Med error og dropdown</h2>
      <pkt-input-wrapper
        label="Etikett"
        helptext="Dette er tekst over bryterne"
        helptextDropdown="Bruk dette tekstfeltet til å skrive mer informasjon om inputfeltet."
        helptextDropdownButton="Les mer"
        optionalTag
        optionalText="Valgfritt"
        :hasError="true"
        errorMessage="Dette er en feilmelding"
        forId="switchGroup3"
        hasFieldset
      >
        <PktCheckbox
          isSwitch
          v-for="(item, index) in switchGroup3"
          :key="index"
          :id="item.id"
          :label="item.label"
          v-model="item.checked"
          @change="handleChange(item.id)"
          :hasTile="false"
          :hasError="!item.checked"
        >
        </PktCheckbox>
      </pkt-input-wrapper>

      <p>Group Switch Values:</p>
      <ul>
        <li v-for="(item, index) in switchGroup3" :key="index">{{ item.label }}: {{ item.checked }}</li>
      </ul>
    </section>

    <section class="component">
      <h2>Disabled</h2>
      <pkt-input-wrapper
        label="Disabled switch group"
        helptext="This is a switch group"
        helptextDropdown="This is a dropdown helptext"
        helptextDropdownButton="This is a dropdown button"
        requiredTag
        requiredText="Required"
        :hasError="true"
        errorMessage="This is an error message"
        :disabled="true"
        forId="switchGroup2"
        hasFieldset
      >
        <PktCheckbox
          isSwitch
          v-for="(item, index) in switchGroup2"
          :key="index"
          :id="item.id"
          :label="item.label"
          v-model="item.checked"
          @change="handleSwitchChange(item.id)"
          :hasFieldset="true"
          :hasTile="true"
          disabled
        >
        </PktCheckbox>
      </pkt-input-wrapper>
    </section>
  </page-main>
</template>

<script>
import PageMain from '@/dev-components/PageMain.vue'
import { PktCheckbox } from '@/components/checkbox'
import { PktInputWrapper } from '@/components/inputwrapper'

export default {
  name: 'Switch',
  components: {
    PktCheckbox,
    PageMain,
    PktInputWrapper,
  },
  data() {
    return {
      singleSwitchValue: false,
      defaultSingleSwitchValue: true,
      switchGroup: [
        {
          id: 'switch1',
          label: 'Apples',
          checked: false,
          checkHelptext: 'Denne valgfrie teksten kan brukes til å beskrive etiketten mer detaljert.',
        },
        { id: 'switch2', label: 'Banana', checked: false },
        { id: 'switch3', label: 'Orange', checked: false },
      ],
      switchGroup2: [
        { id: 'switch4', label: 'Apples', checked: false },
        { id: 'switch5', label: 'Banana', checked: false },
        { id: 'switch6', label: 'Orange', checked: false },
      ],
      switchGroup3: [
        { id: 'switch7', label: 'Apples', checked: false },
        { id: 'switch8', label: 'Banana', checked: false },
        { id: 'switch9', label: 'Orange', checked: false },
      ],
    }
  },
  methods: {
    handleCustomChange(newValue) {
      console.log(`Custom onChange event triggered with value ${newValue}`)
    },
    handleChange(id) {
      const switchEl = this.switchGroup.find((item) => item.id === id)
      if (switchEl) {
        console.log(`Switch ${switchEl.label} is checked: ${switchEl.checked}`)
      }
    },
  },
}
</script>

// packages/react/src/routes/switch.tsx
import React, { useRef } from 'react'

import { PktCheckbox, PktInputWrapper } from '..'

export default function Switch() {
  const checkboxRef = useRef<HTMLInputElement | null>(null)

  const handleCheckboxChange = (id: string, label: string, checked: boolean) => {
    console.log(`Switch with id ${id} and label "${label}" checked:`, checked)
  }

  return (
    <>
      <main className="page-main pkt-container">
        <h1>Switch</h1>

        <section className="component">
          <PktCheckbox
            isSwitch
            id="checboxSingle"
            label="Switch"
            onChange={() =>
              handleCheckboxChange(
                'checboxSingle',
                'Checkbox',
                checkboxRef.current?.checked || false,
              )
            }
            ref={checkboxRef}
          />
          <p>
            Med <code>labelPosition</code> kan man legge label til venstre:
          </p>
          <PktCheckbox
            isSwitch
            id="checboxSingle2"
            label="Switch"
            labelPosition="left"
            onChange={() =>
              handleCheckboxChange(
                'checboxSingle2',
                'Checkbox',
                checkboxRef.current?.checked || false,
              )
            }
            ref={checkboxRef}
          />
          <p>Switch kan også presenteres med en skjult label:</p>
          <PktCheckbox
            isSwitch
            id="checboxSingle3"
            label="Switch"
            hideLabel
            onChange={() =>
              handleCheckboxChange(
                'checboxSingle3',
                'Checkbox',
                checkboxRef.current?.checked || false,
              )
            }
            ref={checkboxRef}
          />
        </section>

        <section className="component">
          <PktCheckbox
            isSwitch
            id="checkboxHelptext"
            label="Switch med hjelpetekst"
            checkHelptext="Denne valgfrie teksten kan brukes til å beskrive etiketten mer detaljert."
            onChange={() =>
              handleCheckboxChange(
                'checkboxHelptext',
                'Checkbox med hjelpetekst',
                checkboxRef.current?.checked || false,
              )
            }
            ref={checkboxRef}
          />
        </section>

        <section className="component">
          <PktCheckbox
            isSwitch
            id="checkboxHelptext2"
            label="Switch med hjelpetekst til venstre og default checked"
            labelPosition="left"
            checkHelptext="Denne valgfrie teksten kan brukes til å beskrive etiketten mer detaljert."
            defaultChecked
            onChange={() =>
              handleCheckboxChange(
                'checkboxHelptext2',
                'Checkbox med hjelpetekst',
                checkboxRef.current?.checked || false,
              )
            }
            ref={checkboxRef}
          />
        </section>

        <section className="component">
          <PktCheckbox
            isSwitch
            id="checkboxWithDefaultChecked"
            label="Switch med default checked og disabled"
            disabled
            defaultChecked
            onChange={() =>
              handleCheckboxChange(
                'checkboxGroupInputwrapper',
                'Checkbox med inputwrapper',
                checkboxRef.current?.checked || false,
              )
            }
          />
        </section>

        <section className="component">
          <PktCheckbox
            isSwitch
            id="checkboxWithDefaultChecked2"
            label="Switch med tile, default checked og disabled"
            disabled
            hasTile
            defaultChecked
            onChange={() =>
              handleCheckboxChange(
                'checkboxGroupInputwrapper2',
                'Checkbox med inputwrapper tile disabled',
                checkboxRef.current?.checked || false,
              )
            }
          />
        </section>

        <section className="component">
          <h2>Med inputwrapper</h2>
          <PktInputWrapper
            label="Etikett"
            helptext="Dette er tekst over avmerkingsboksene."
            optionalTag
            optionalText="Valgfritt"
            forId="checkboxGroup3"
            hasFieldset
          >
            <PktCheckbox
              isSwitch
              key="checkboxGroupInputwrapper"
              id="checkboxGroupInputwrapper"
              label="Switch med inputwrapper"
              checkHelptext="Denne valgfrie teksten kan brukes til å beskrive etiketten mer
                            detaljert."
              onChange={() =>
                handleCheckboxChange(
                  'checkboxGroupInputwrapper',
                  'Checkbox med inputwrapper',
                  checkboxRef.current?.checked || false,
                )
              }
              ref={checkboxRef}
            />
            <PktCheckbox
              isSwitch
              key="checkboxGroupInputwrapper2"
              id="checkboxGroupInputwrapper2"
              label="Switch med inputwrapper"
              onChange={() =>
                handleCheckboxChange(
                  'checkboxGroupInputwrapper2',
                  'Checkbox med inputwrapper',
                  checkboxRef.current?.checked || false,
                )
              }
              ref={checkboxRef}
            />
            <PktCheckbox
              isSwitch
              key="checkboxGroupInputwrapper3"
              id="checkboxGroupInputwrapper3"
              label="Switch med inputwrapper"
              onChange={() =>
                handleCheckboxChange(
                  'checkboxGroupInputwrapper3',
                  'Checkbox med inputwrapper',
                  checkboxRef.current?.checked || false,
                )
              }
              ref={checkboxRef}
            />
          </PktInputWrapper>
        </section>

        <section className="component">
          <h2>Med inputwrapper</h2>
          <PktInputWrapper
            label="Etikett"
            helptext="Dette er tekst over checkboxene"
            helptextDropdown="Bruk dette tekstfeltet til å skrive mer informasjon om inputfeltet."
            helptextDropdownButton="Les mer"
            optionalTag
            optionalText="Valgfritt"
            forId="checkboxGroup3"
            hasFieldset
            hasError
            errorMessage="Dette er en feilmelding"
          >
            <PktCheckbox
              isSwitch
              key="checkboxError"
              id="checkboxError"
              label="Switch med error"
              checkHelptext="Denne valgfrie teksten kan brukes til å beskrive etiketten mer
                            detaljert."
              onChange={() =>
                handleCheckboxChange(
                  'checkboxError',
                  'Checkbox med error',
                  checkboxRef.current?.checked || false,
                )
              }
              ref={checkboxRef}
              hasTile
              hasError
            />
            <PktCheckbox
              isSwitch
              key="checkboxError2"
              id="checkboxError2"
              label="Switch med inputwrapper"
              onChange={() =>
                handleCheckboxChange(
                  'checkboxError2',
                  'Checkbox med error',
                  checkboxRef.current?.checked || false,
                )
              }
              ref={checkboxRef}
              hasTile
              hasError
            />
            <PktCheckbox
              isSwitch
              key="checkboxError3"
              id="checkboxError3"
              label="Switch med error"
              onChange={() =>
                handleCheckboxChange(
                  'checkboxError3',
                  'Checkbox med error',
                  checkboxRef.current?.checked || false,
                )
              }
              ref={checkboxRef}
              hasTile
              hasError
            />
          </PktInputWrapper>
        </section>
      </main>
    </>
  )
}
