// packages/vue2/src/views/Tag.vue
<template>
  <page-main class="pkt-container pkt-container--laptop">
    <h1>Tag</h1>

    <section class="component">
      <pkt-tag>Tag</pkt-tag>
      <pkt-tag skin="red">Tag</pkt-tag>
      <pkt-tag skin="yellow">Tag</pkt-tag>
      <pkt-tag skin="green">Tag</pkt-tag>
      <pkt-tag skin="beige">Tag</pkt-tag>
      <pkt-tag skin="grey">Tag</pkt-tag>
      <pkt-tag skin="blue-light">Tag</pkt-tag>
      <h2>Tag med ikon</h2>
      <pkt-tag iconName="edit">Tag</pkt-tag>
      <pkt-tag iconName="clock" skin="red">Tag</pkt-tag>
      <pkt-tag iconName="plus-sign" skin="yellow">Tag</pkt-tag>
      <pkt-tag iconName="check-big" skin="green">Tag</pkt-tag>
      <pkt-tag iconName="chevron-right" skin="beige">Tag</pkt-tag>
      <pkt-tag iconName="edit" skin="grey">Tag</pkt-tag>
      <h2>Tag med close</h2>
      <pkt-tag closeTag>Tag</pkt-tag>
      <pkt-tag closeTag skin="red" ariaLabel="fjern dine valg">Tag</pkt-tag>
      <pkt-tag closeTag skin="yellow">Tag</pkt-tag>
      <pkt-tag closeTag skin="green">Tag</pkt-tag>
      <pkt-tag closeTag skin="beige">Tag</pkt-tag>
      <pkt-tag closeTag skin="grey">Tag</pkt-tag>
      <h2>Tag med ikon og close</h2>
      <pkt-tag iconName="edit" closeTag>Tag</pkt-tag>
      <pkt-tag iconName="clock" closeTag skin="red">Tag</pkt-tag>
      <pkt-tag iconName="plus-sign" closeTag skin="yellow">Tag</pkt-tag>
      <pkt-tag iconName="check-big" closeTag skin="green">Tag</pkt-tag>
      <pkt-tag iconName="chevron-right" closeTag skin="beige">Tag</pkt-tag>
      <pkt-tag iconName="edit" closeTag skin="grey">Tag</pkt-tag>
      <h2>Tag størrelser</h2>
      <pkt-tag size="large" iconName="edit" closeTag>Large</pkt-tag>
      <pkt-tag size="medium" iconName="edit" closeTag>Medium</pkt-tag>
      <pkt-tag size="small" iconName="edit" closeTag>Small</pkt-tag>
      <h2>Tag tekst-style</h2>
      <pkt-tag textStyle="thin-text">Thin</pkt-tag>
      <pkt-tag textStyle="normal-text">Normal</pkt-tag>
    </section>
  </page-main>
</template>

<script>
import PageMain from '@/dev-components/PageMain.vue';
import { PktTag } from '@/components/tag';

export default {
  name: 'BackLink',
  components: {
    PktTag,
    PageMain,
  },
  data: () => ({}),
};
</script>

<style lang="scss"></style>

// packages/react/src/routes/tag.tsx
import TagSpec from 'componentSpecs/tag.json'
import React, { useState } from 'react'

import { IPktTag } from '@/components/tag/Tag'
import ITagSpec from '@/interfaces/ITagSpec'

import { PktTag } from '..'


export default function Tag() {
    const tagSpec = TagSpec as ITagSpec
    const [specProps] = useState(tagSpec.props)

    return (

        <main className="page-main pkt-container">
            <h1>Tag</h1>
            {Array.isArray(specProps.skin.values) &&
                specProps.skin.values.map((skinType: IPktTag['skin'], index: number) => (
                    <section className="component" key={`skin-${index}`}>
                        <h2>Skin: {skinType}</h2>
                        {Array.isArray(specProps.size.values) && specProps.size.values.map((sizeType: IPktTag['size'], i: number) => (
                            <React.Fragment key={`size-${i}`} >

                                <PktTag
                                    key={`skin-${index}-${skinType}`}
                                    skin={skinType}
                                    size={sizeType}
                                >
                                    Test
                                </PktTag>
                            </React.Fragment>
                        ))}
                    </section>
                ))}

            <h1>Tag med close</h1>
            <section className="component">
                {Array.isArray(specProps.size.values) && specProps.size.values.map((sizeType: IPktTag['size'], i: number) => (

                    <PktTag
                        key={`${i}-${sizeType}`}
                        size={sizeType}
                        closeTag
                    >
                        Test
                    </PktTag>

                ))}
            </section>

            <h1>Tag med ikon</h1>
            <section className="component">
                {Array.isArray(specProps.size.values) && specProps.size.values.map((sizeType: IPktTag['size'], i: number) => (

                    <PktTag
                        key={`${i}-${sizeType}`}
                        size={sizeType}
                        iconName='edit'
                    >
                        Test
                    </PktTag>

                ))}
            </section>

            <h1>Tag med ikon og close</h1>
            <section className="component">
                {Array.isArray(specProps.size.values) && specProps.size.values.map((sizeType: IPktTag['size'], i: number) => (

                    <PktTag
                        key={`${i}-${sizeType}`}
                        size={sizeType}
                        iconName='edit'
                        closeTag
                    >
                        Test
                    </PktTag>

                ))}
            </section>

            <h1>Tag tekst style</h1>
            <section className="component">
                {Array.isArray(specProps.textStyle.values) && specProps.textStyle.values.map((textType: IPktTag['textStyle'], i: number) => (

                    <PktTag
                        key={`${i}-${textType}`}
                        textStyle={textType}
                    >
                        {textType}
                    </PktTag>

                ))}
            </section>

        </main >

    )
}
