// packages/react/src/components/linkcard/LinkCard.tsx
import React, { ForwardedRef, forwardRef } from 'react'

import { PktIcon } from '../icon/Icon'

export interface IPktLinkCard extends React.HTMLAttributes<HTMLAnchorElement> {
  skin?: 'normal' | 'blue' | 'beige' | 'beige-outline' | 'grey-outline'
  title?: string
  href?: string
  iconName?: string
  openInNewTab?: boolean
  external?: boolean
}

export const PktLinkCard = forwardRef(
  (
    {
      children,
      className,
      iconName = 'user',
      openInNewTab = false,
      skin = 'normal',
      href = '#',
      external = false,
      title,
      ...props
    }: IPktLinkCard,
    ref: ForwardedRef<HTMLAnchorElement>,
  ) => {
    const classes = [className, 'pkt-linkcard', skin && `pkt-linkcard--${skin}`]
      .filter(Boolean)
      .join(' ')
    return (
      <a
        {...props}
        href={href}
        className={`pkt-linkcard pkt-link ${classes}`}
        target={openInNewTab ? '_blank' : '_self'}
        rel={openInNewTab ? 'noopener noreferrer' : undefined}
        ref={ref}
      >
        <PktIcon className="pkt-link__icon" name={iconName}></PktIcon>
        <div className="pkt-linkcard__content">
          <div className={`pkt-linkcard__title ${external ? 'pkt-link pkt-link--external' : ''}`}>
            {title}
          </div>
          <div className="pkt-linkcard__text">{children}</div>
        </div>
      </a>
    )
  },
)

PktLinkCard.displayName = 'PktLinkCard'

// packages/vue/src/components/linkcard/Linkcard.vue
<template>
  <a
    :href="href"
    class="pkt-linkcard pkt-link"
    :class="skin ? `pkt-linkcard--${this.skin}` : 'normal'"
    :target="openInNewTab ? '_blank' : '_self'"
    :rel="openInNewTab ? 'noopener noreferrer' : undefined"
  >
    <pkt-icon class="pkt-link__icon" :name="iconName"></pkt-icon>
    <div class="pkt-linkcard__content">
      <div :class="['pkt-linkcard__title', { 'pkt-link pkt-link--external': external }]">
        {{ title }}
      </div>
      <div class="pkt-linkcard__text">
        <slot />
      </div>
    </div>
  </a>
</template>

<script>
import PktIcon from '../icon/Icon.vue';
export default {
  name: 'PktLinkcard',
  components: {
    PktIcon,
  },
  props: {
    skin: {
      type: String,
      default: 'normal',
      validator(value) {
        return ['normal', 'blue', 'beige', 'beige-outline', 'grey-outline'].includes(value);
      },
    },
    title: {
      type: String,
      default: '',
    },
    href: {
      type: String,
      default: '',
    },
    iconName: {
      type: String,
      default: '',
    },
    openInNewTab: {
      type: Boolean,
      default: false,
    },
    external: {
      type: Boolean,
      default: false,
    },
  },
  methods: {},
};
</script>
