// packages/react/src/components/textarea/Textarea.tsx
import {
  ChangeEvent,
  ForwardedRef,
  forwardRef,
  TextareaHTMLAttributes,
  useEffect,
  useRef,
  useState,
} from 'react'

import { PktInputWrapper } from '../inputwrapper/InputWrapper'

export interface IPktTextareaProps extends TextareaHTMLAttributes<HTMLTextAreaElement> {
  id: string
  ariaDescribedby?: string
  ariaLabelledby?: string
  counter?: boolean
  counterMaxLength?: number
  disabled?: boolean
  errorMessage?: string
  hasError?: boolean
  helptext?: string
  helptextDropdown?: string
  helptextDropdownButton?: string
  inline?: boolean
  fullwidth?: boolean
  label: string
  name?: string
  optionalTag?: boolean
  optionalText?: string
  requiredTag?: boolean
  requiredText?: string
  placeholder?: string
  rows?: number
  useWrapper?: boolean
}

export const PktTextarea = forwardRef(
  (
    {
      id,
      ariaDescribedby,
      ariaLabelledby,
      counter,
      counterMaxLength,
      className,
      disabled,
      errorMessage,
      hasError,
      helptext,
      helptextDropdown,
      helptextDropdownButton,
      inline,
      fullwidth = false,
      label,
      name,
      optionalTag = false,
      optionalText,
      requiredTag = false,
      requiredText,
      placeholder,
      rows,
      useWrapper = true,
      onChange,
      ...props
    }: IPktTextareaProps,
    ref: ForwardedRef<HTMLTextAreaElement>,
  ) => {
    const classNames = [className, 'pkt-textinput', 'pkt-textarea'].join(' ')
    const labelledBy = ariaLabelledby || `${id}-label`

    const internalRef = useRef<HTMLTextAreaElement>(null)

    const [counterCurrent, setCounterCurrent] = useState(0)

    const handleChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
      counter && setCounterCurrent(e.currentTarget?.value?.length || 0)
      if (onChange) {
        return onChange(e)
      }
    }

    useEffect(() => {
      typeof ref === 'function' && ref(internalRef.current)
      counter && setCounterCurrent(internalRef?.current?.value?.length || 0)
    }, [ref])

    return (
      <PktInputWrapper
        ariaDescribedby={ariaDescribedby}
        className={classNames}
        disabled={disabled}
        errorMessage={errorMessage}
        forId={id}
        hasError={hasError}
        helptext={helptext}
        helptextDropdown={helptextDropdown}
        helptextDropdownButton={helptextDropdownButton}
        inline={inline}
        label={label}
        optionalTag={optionalTag}
        optionalText={optionalText}
        requiredTag={requiredTag}
        requiredText={requiredText}
        useWrapper={useWrapper}
      >
        <textarea
          ref={internalRef}
          className={`pkt-input ${fullwidth ? 'pkt-input--fullwidth' : ''} ${
            counterMaxLength && counterCurrent > counterMaxLength ? 'pkt-input--counter-error' : ''
          }`}
          name={name || id}
          id={id}
          placeholder={placeholder}
          disabled={disabled}
          rows={rows}
          aria-labelledby={labelledBy}
          aria-invalid={hasError}
          aria-errormessage={`${id}-error`}
          {...props}
          onChange={handleChange}
        />
        {counter && (
          <div className="pkt-input__counter" aria-live="polite" aria-atomic={true}>
            {counterCurrent || 0}
            {counterMaxLength && `/${counterMaxLength}`}
          </div>
        )}
      </PktInputWrapper>
    )
  },
)

// packages/vue2/src/components/textarea/Textarea.vue
<template>
  <PktInputWrapper
    class="pkt-textarea"
    :forId="id"
    :label="label"
    :helptext="helptext"
    :helptextDropdown="helptextDropdown"
    :helptextDropdownButton="helptextDropdownButton"
    :optionalTag="optionalTag"
    :optionalText="optionalText"
    :requiredTag="requiredTag"
    :requiredText="requiredText"
    :hasError="hasError"
    :errorMessage="errorMessage"
    :disabled="disabled"
    :inline="inline"
    :ariaDescribedby="ariaDescribedby"
    :useWrapper="useWrapper"
    @toggleHelpText="$emit('toggleHelpText')"
  >
    <textarea
      v-bind="$attrs"
      v-on="{
        ...$listeners,
        input: (event) => $emit('input', event.target.value),
      }"
      :class="{
        'pkt-input': true,
        'pkt-input--fullwidth': fullwidth,
        'pkt-input--counter-error': counterMaxLength && value?.length > counterMaxLength,
      }"
      :aria-invalid="hasError"
      :aria-errormessage="hasError ? `${id}-error` : ''"
      :aria-labelledby="labelledBy"
      :disabled="disabled"
      :id="id"
      :name="name || id"
      :placeholder="placeholder"
      :rows="rows"
      :value="value"
    />
    <div v-if="counter" class="pkt-input__counter" aria-live="polite" aria-atomic="true">
      {{ value?.length || 0 }}<template v-if="counterMaxLength">/{{ counterMaxLength }}</template>
    </div>
  </PktInputWrapper>
</template>

<script>
import PktIcon from '../icon/Icon.vue'
import PktAlert from '../alert/Alert.vue'
import PktButton from '../button/Button.vue'
import PktInputWrapper from '../inputwrapper/InputWrapper.vue'

export default {
  name: 'PktTextarea',
  components: { PktIcon, PktAlert, PktButton, PktInputWrapper },
  inheritAttrs: false,
  props: {
    label: {
      type: String,
      required: true,
      default: 'input',
    },
    helptext: {
      type: String,
      required: false,
    },
    helptextDropdown: {
      type: String,
      required: false,
    },
    helptextDropdownButton: {
      type: String,
      required: false,
    },
    optionalTag: {
      type: Boolean,
      required: false,
      default: false,
    },
    optionalText: {
      type: String,
      required: false,
    },
    requiredTag: {
      type: Boolean,
      required: false,
      default: false,
    },
    requiredText: {
      type: String,
      required: false,
    },
    hasError: {
      type: Boolean,
      required: false,
    },
    errorMessage: {
      type: String,
      required: false,
    },
    name: {
      type: String,
      required: false,
    },
    id: {
      type: String,
      required: true,
    },
    placeholder: {
      type: String,
      required: false,
    },
    value: {
      type: String,
      required: false,
    },
    disabled: {
      type: Boolean,
      required: false,
      default: false,
    },
    inline: {
      type: Boolean,
      required: false,
      default: false,
    },
    fullwidth: {
      type: Boolean,
      default: false,
    },
    ariaLabelledby: {
      type: String,
      required: false,
    },
    ariaDescribedby: {
      type: String,
      required: false,
    },
    counter: {
      type: Boolean,
      default: false,
    },
    counterMaxLength: {
      type: Number,
      required: false,
    },
    rows: {
      type: Number,
      required: false,
    },
    useWrapper: {
      type: Boolean,
      default: true,
    },
  },
  computed: {
    labelledBy() {
      this.ariaLabelledby || `${this.id}-label`
    },
  },
}
</script>
