// packages/vue2/src/components/alert/Alert.vue
<template>
  <div
    :class="{ 'pkt-alert': true, [skinClass]: true, 'pkt-alert--compact': compact }"
    v-show="open"
    :aria-live="ariaLive"
  >
    <pkt-icon :name="iconName" class="pkt-alert__icon"></pkt-icon>

    <div class="pkt-alert__close" v-if="closeAlert">
      <button
        class="pkt-btn pkt-btn--tertiary pkt-btn--small pkt-btn--icon-only"
        type="button"
        role="button"
        tabindex="0"
        aria-label="close"
        @keyup.enter="close"
        @click="close"
      >
        <pkt-icon class="pkt-btn__icon" name="close"></pkt-icon>
      </button>
    </div>

    <div class="pkt-alert__title" v-if="title">
      {{ title }}
    </div>

    <div class="pkt-alert__text"><slot /></div>

    <div class="pkt-alert__date" v-if="date">Sist oppdatert: {{ date }}</div>
  </div>
</template>

<script>
import PktIcon from '../icon/Icon.vue'
export default {
  name: 'PktAlert',
  components: {
    PktIcon,
  },
  props: {
    skin: {
      type: String,
      default: 'info',
      validator(value) {
        return ['error', 'success', 'warning', 'info'].includes(value)
      },
    },
    closeAlert: {
      type: Boolean,
      default: false,
    },
    title: {
      type: String,
      default: '',
    },
    date: {
      type: String,
      default: '',
    },
    ariaLive: {
      type: String,
      default: 'polite',
      validator(value) {
        return ['off', 'polite', 'assertive'].includes(value)
      },
    },
    compact: {
      type: Boolean,
      default: false,
    },
  },
  data: () => ({
    closed: false,
  }),
  methods: {
    close() {
      this.closed = true
      this.$emit('on-close', this.closed)
    },
  },
  computed: {
    skinClass() {
      return [`pkt-alert--${this.skin}`]
    },
    open() {
      return !this.closed
    },
    iconName() {
      return this.skin === 'info' ? 'alert-information' : `alert-${this.skin}`
    },
  },
}
</script>

// packages/react/src/components/alert/Alert.tsx
import React, { ForwardedRef, forwardRef, useState } from 'react'

import { PktIcon } from '../icon/Icon'

export interface IPktAlert extends React.HTMLAttributes<HTMLDivElement> {
  skin?: 'error' | 'success' | 'warning' | 'info'
  closeAlert?: boolean
  onClose?: () => void
  title?: string
  date?: string
  ariaLive?: 'off' | 'polite' | 'assertive'
  compact?: boolean
}

export const PktAlert = forwardRef(
  (
    {
      children,
      className,
      skin = 'info',
      closeAlert = false,
      onClose,
      title,
      date,
      ariaLive = 'polite',
      compact = false,
      ...props
    }: IPktAlert,
    ref: ForwardedRef<HTMLDivElement>,
  ) => {
    const classes = [
      className,
      'pkt-alert',
      skin && `pkt-alert--${skin}`,
      compact && 'pkt-alert--compact',
    ]
      .filter(Boolean)
      .join(' ')

    const [isDisplayed, setIsDisplayed] = useState(true)

    const handleClose = () => {
      setIsDisplayed(false)
      if (onClose) {
        onClose()
      }
    }

    return isDisplayed ? (
      <div {...props} className={classes} aria-live={ariaLive} ref={ref}>
        <PktIcon
          className="pkt-alert__icon"
          name={skin === 'info' ? 'alert-information' : `alert-${skin}`}
        />

        {closeAlert && (
          <div className="pkt-alert__close">
            <button
              type="button"
              className="pkt-btn pkt-btn--tertiary pkt-btn--small pkt-btn--icon-only"
              tabIndex={0}
              aria-label="close"
              onClick={handleClose}
            >
              <PktIcon name="close" className="pkt-btn__icon" aria-hidden="true" />
            </button>
          </div>
        )}

        {title && <div className="pkt-alert__title">{title}</div>}

        <div className="pkt-alert__text">{children}</div>

        {date && <div className="pkt-alert__date">Sist oppdatert: {date}</div>}
      </div>
    ) : null
  },
)
