// packages/react/src/components/inputwrapper/InputWrapper.tsx
import React, { ForwardedRef, forwardRef, ReactNode, RefAttributes, useState } from 'react'

import { PktAlert } from '../alert/Alert'
import { PktButton } from '../button/Button'

export interface IPktInputWrapper extends RefAttributes<HTMLElement> {
  forId: string
  label: string
  helptext?: string
  helptextDropdown?: string
  helptextDropdownButton?: string
  optionalTag?: boolean
  optionalText?: string
  requiredTag?: boolean
  requiredText?: string
  hasError?: boolean
  errorMessage?: string
  disabled?: boolean
  inline?: boolean
  ariaDescribedby?: string
  useWrapper?: boolean
  children?: ReactNode
  className?: string
  hasFieldset?: boolean
}

export const PktInputWrapper = forwardRef(
  (
    {
      forId,
      label,
      helptext,
      helptextDropdown,
      helptextDropdownButton,
      optionalTag = false,
      optionalText = 'Valgfritt',
      requiredTag = false,
      requiredText = 'Må fylles ut',
      hasError,
      errorMessage,
      disabled,
      inline,
      ariaDescribedby,
      useWrapper = true,
      children,
      className,
      hasFieldset = false,
    }: IPktInputWrapper,
    ref: ForwardedRef<HTMLDivElement>,
  ) => {
    const [isHelpTextOpen, setIsHelpTextOpen] = useState(false)

    const toggleHelpText = () => {
      setIsHelpTextOpen(!isHelpTextOpen)
    }

    const tagClass = () => {
      if (optionalTag) {
        return 'pkt-tag pkt-tag--small pkt-tag--thin-text pkt-tag--blue-light'
      } else if (requiredTag) {
        return 'pkt-tag pkt-tag--small pkt-tag--thin-text pkt-tag--beige'
      } else {
        return ''
      }
    }

    const tagText = optionalTag ? optionalText : requiredTag ? requiredText : ''

    const disabledClass = disabled ? 'pkt-inputwrapper--disabled' : ''
    const inlineClass = inline ? 'pkt-inputwrapper--inline' : ''
    const errorClass = hasError ? 'pkt-inputwrapper--error' : ''

    const hasDropDown = !!helptextDropdown && helptextDropdown !== ''

    const dropdownButton =
      helptextDropdownButton || 'Les mer <span class="pkt-sr-only">om inputfeltet</span>'

    const LabelComponent = hasFieldset ? 'fieldset' : hasDropDown ? 'div' : 'label'
    const LabelTextComponent = hasFieldset ? 'legend' : hasDropDown ? 'h2' : 'span'

    const describedBy = ariaDescribedby
      ? ariaDescribedby
      : helptext
      ? `${forId}-helptext`
      : undefined

    return (
      <div
        className={['pkt-inputwrapper', className, disabledClass, inlineClass, errorClass].join(
          ' ',
        )}
        ref={ref}
      >
        {useWrapper ? (
          <>
            <LabelComponent
              htmlFor={!hasFieldset ? forId : undefined}
              aria-describedby={hasDropDown ? undefined : ariaDescribedby}
              className={`pkt-inputwrapper__label${
                hasFieldset ? ' pkt-inputwrapper__fieldset' : ''
              }`}
            >
              <LabelTextComponent
                id={`${forId}-label`}
                className={`${hasFieldset ? ' pkt-inputwrapper__legend' : ''}`}
              >
                {label}
                {tagText !== '' && <span className={tagClass()}>{tagText}</span>}
              </LabelTextComponent>
              {helptext && (
                <div
                  className="pkt-inputwrapper__helptext"
                  id={`${forId}-helptext`}
                  dangerouslySetInnerHTML={{ __html: helptext }}
                ></div>
              )}
              {hasDropDown && helptextDropdown !== '' && (
                <div>
                  <PktButton
                    skin="tertiary"
                    size="small"
                    variant="icon-right"
                    iconName={isHelpTextOpen ? 'chevron-thin-up' : 'chevron-thin-down'}
                    className="pkt-inputwrapper__helptext-expandable pkt-link pkt-link--icon-right"
                    onClick={toggleHelpText}
                  >
                    <span dangerouslySetInnerHTML={{ __html: dropdownButton }} />
                  </PktButton>
                  <div
                    className={`pkt-inputwrapper__helptext ${
                      isHelpTextOpen
                        ? 'pkt-inputwrapper__helptext-expandable-open'
                        : 'pkt-inputwrapper__helptext-expandable-closed'
                    }`}
                  >
                    <span dangerouslySetInnerHTML={{ __html: helptextDropdown }} />
                  </div>
                  {!hasFieldset && (
                    <label htmlFor={forId} className="pkt-sr-only" aria-describedby={describedBy}>
                      {label}
                    </label>
                  )}
                </div>
              )}
              <>{children}</>
            </LabelComponent>
          </>
        ) : (
          <>
            {!hasFieldset && (
              <label
                htmlFor={forId}
                className="pkt-sr-only"
                aria-describedby={describedBy}
                id={`${forId}-label`}
              >
                {label}
              </label>
            )}
            {children}
          </>
        )}
        {hasError && errorMessage && (
          <div>
            <PktAlert skin="error" aria-live="assertive" id={`${forId}-error`} compact>
              {errorMessage}
            </PktAlert>
          </div>
        )}
      </div>
    )
  },
)

PktInputWrapper.displayName = 'PktInputWrapper'

// packages/vue2/src/components/inputwrapper/InputWrapper.vue
<template>
  <div :class="['pkt-inputwrapper', disabledClass, inlineClass, errorClass]">
    <template v-if="useWrapper">
      <component
        :is="hasFieldset ? 'fieldset' : hasDropDown ? 'div' : 'label'"
        :for="!hasFieldset ? forId : undefined"
        class="pkt-inputwrapper__label"
        :class="{
          'pkt-inputwrapper__fieldset': hasFieldset,
          'pkt-inputwrapper__legend': hasFieldset,
        }"
        :aria-describedby="hasDropDown ? undefined : ariaDescribedby"
      >
        <component
          :class="{
            'pkt-inputwrapper__legend': hasFieldset,
          }"
          :is="hasFieldset ? 'legend' : hasDropDown ? 'h2' : 'span'"
          :id="`${forId}-label`"
          >{{ label }}<span v-if="tagText !== ''" :class="tagClass()">{{ tagText }}</span></component
        >
        <div v-if="helptext" class="pkt-inputwrapper__helptext" :id="`${forId}-helptext`" v-html="helptext"></div>

        <template v-if="hasDropDown">
          <pkt-button
            skin="tertiary"
            size="small"
            variant="icon-right"
            :icon-name="isHelpTextOpen ? 'chevron-thin-up' : 'chevron-thin-down'"
            class="pkt-inputwrapper__helptext-expandable pkt-link pkt-link--icon-right"
            @onClick="toggleHelpText"
          >
            <span v-html="dropdownButton"></span>
          </pkt-button>

          <div
            class="pkt-inputwrapper__helptext"
            :class="{
              'pkt-inputwrapper__helptext-expandable-open': isHelpTextOpen,
              'pkt-inputwrapper__helptext-expandable-closed': !isHelpTextOpen,
            }"
          >
            <span v-html="helptextDropdown"></span>
          </div>

          <label v-if="!hasFieldset" :for="forId" class="pkt-sr-only" :aria-describedby="describedBy">{{
            label
          }}</label>
        </template>
        <slot />
      </component>
    </template>
    <template v-else>
      <label
        v-if="!hasFieldset"
        :for="forId"
        class="pkt-sr-only"
        :aria-describedby="describedBy"
        :id="`${forId}-label`"
        >{{ label }}</label
      >
      <slot />
    </template>
    <div v-if="hasError && errorMessage">
      <pkt-alert skin="error" aria-live="assertive" :id="`${forId}-error`" compact>{{ errorMessage }}</pkt-alert>
    </div>
  </div>
</template>

<script>
import PktAlert from '../alert/Alert.vue'
import PktButton from '../button/Button.vue'

export default {
  name: 'pktInputwrapper',
  components: { PktAlert, PktButton },
  inheritAttrs: false,
  props: {
    forId: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      required: true,
      default: 'input',
    },
    helptext: {
      type: String,
      required: false,
    },
    helptextDropdown: {
      type: String,
      required: false,
    },
    helptextDropdownButton: {
      type: String,
      required: false,
    },
    optionalTag: {
      type: Boolean,
      required: false,
      default: false,
    },
    optionalText: {
      type: String,
      default: 'Valgfritt',
    },
    requiredTag: {
      type: Boolean,
      required: false,
      default: false,
    },
    requiredText: {
      type: String,
      default: 'Må fylles ut',
    },
    hasError: {
      type: Boolean,
      required: false,
    },
    errorMessage: {
      type: String,
      required: false,
    },
    disabled: {
      type: Boolean,
      required: false,
      default: false,
    },
    inline: {
      type: Boolean,
      required: false,
      default: false,
    },
    ariaDescribedby: {
      type: String,
      required: false,
    },
    useWrapper: {
      type: Boolean,
      default: true,
    },
    hasFieldset: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      isHelpTextOpen: false,
    }
  },
  methods: {
    toggleHelpText() {
      this.isHelpTextOpen = !this.isHelpTextOpen
      this.$emit('toggleHelpText', this.isHelpTextOpen)
    },
    tagClass() {
      return this.optionalTag
        ? 'pkt-tag pkt-tag--small pkt-tag--thin-text pkt-tag--blue-light'
        : this.requiredTag
        ? 'pkt-tag pkt-tag--small pkt-tag--thin-text pkt-tag--beige'
        : ''
    },
  },
  computed: {
    tagText() {
      return this.optionalTag ? this.optionalText : this.requiredTag ? this.requiredText : ''
    },
    disabledClass() {
      return this.disabled ? 'pkt-inputwrapper--disabled' : ''
    },
    inlineClass() {
      return this.inline ? 'pkt-inputwrapper--inline' : ''
    },
    errorClass() {
      return this.hasError ? 'pkt-inputwrapper--error' : ''
    },
    hasDropDown() {
      return !!this.helptextDropdown && this.helptextDropdown !== ''
    },
    dropdownButton() {
      return this.helptextDropdownButton || 'Les mer <span class="pkt-sr-only">om inputfeltet</span>'
    },
    describedBy() {
      this.ariaDescribedby ? this.ariaDescribedby : this.helptext ? `${this.forId}-helptext` : undefined
    },
  },
}
</script>
