// packages/vue2/src/components/messagebox/Messagebox.vue
<template>
  <div :class="{ 'pkt-messagebox': true, [skinClass]: true, 'pkt-messagebox--compact': compact }">
    <div class="pkt-messagebox__title">
      {{ title }}
    </div>

    <div class="pkt-messagebox__text"><slot /></div>
  </div>
</template>

<script>
export default {
  name: 'PktMessagebox',
  props: {
    skin: {
      type: String,
      default: 'beige',
      validator(value) {
        return ['beige', 'green', 'red', 'blue'].includes(value);
      },
    },

    title: {
      type: String,
      default: '',
    },
    compact: {
      type: Boolean,
      default: false,
    },
  },
  computed: {
    skinClass() {
      return [`pkt-messagebox--${this.skin}`];
    },
  },
};
</script>

// packages/react/src/components/messagebox/Messagebox.tsx
import React from 'react'

export interface IPktMessagebox extends React.HTMLAttributes<HTMLDivElement> {
  skin?: 'beige' | 'red' | 'green' | 'blue'
  title?: string
  compact?: boolean
}

export const PktMessagebox: React.FC<IPktMessagebox> = ({
  children,
  className,
  compact = false,
  skin = 'beige',
  title,
  ...props
}) => {
  const classes = [
    className,
    'pkt-messagebox',
    skin && `pkt-messagebox--${skin}`,
    compact && 'pkt-messagebox--compact',
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div {...props} className={classes}>
      { title && <div className="pkt-messagebox__title">{title}</div> }

      <div className="pkt-messagebox__text">{children}</div>
    </div>
  )
}
