// packages/vue2/src/components/footer/Footer.vue
<template>
  <footer class="pkt-footer" data-mode="dark">
    <div class="pkt-footer__container">
      <div class="pkt-grid pkt-grid--rowgap-size-32 pkt-grid--gap-size-16">
        <div class="pkt-footer__column pkt-cell pkt-cell--span12 pkt-cell--span4-laptop-up">
          <h2 class="pkt-footer__title">{{ columnOne.title }}</h2>
          <ul class="pkt-footer__list">
            <li class="pkt-footer__text" v-if="columnOne.text">
              {{ columnOne.text }}
            </li>
            <li class="pkt-footer__list-item" v-for="(link, index) in columnOne.links" :key="`links-${index}`">
              <a
                class="pkt-footer__link"
                :href="link.href"
                :class="{ 'pkt-link--external': link.external }"
                :target="link.openInNewTab ? '_blank' : '_self'"
                :rel="link.openInNewTab ? 'noopener noreferrer' : undefined"
              >
                <pkt-icon class="pkt-footer__link-icon" name="chevron-right"></pkt-icon>
                {{ link.text }}
              </a>
            </li>
          </ul>
        </div>
        <div class="pkt-footer__column pkt-cell pkt-cell--span12 pkt-cell--span4-laptop-up">
          <h2 class="pkt-footer__title">{{ columnTwo.title }}</h2>
          <ul class="pkt-footer__list">
            <li class="pkt-footer__list-item" v-for="(link, index) in columnTwo.links" :key="`links-${index}`">
              <a
                class="pkt-footer__link"
                :href="link.href"
                :class="{ 'pkt-link--external': link.external }"
                :target="link.openInNewTab ? '_blank' : '_self'"
                :rel="link.openInNewTab ? 'noopener noreferrer' : undefined"
              >
                <pkt-icon class="pkt-footer__link-icon" name="chevron-right"></pkt-icon>
                {{ link.text }}
              </a>
            </li>
          </ul>
        </div>
        <div class="pkt-footer__column pkt-cell pkt-cell--span12 pkt-cell--span4-laptop-up">
          <h2 class="pkt-footer__title">Om nettstedet</h2>
          <ul class="pkt-footer__list">
            <li class="pkt-footer__list-item">
              <a :href="personvernOgInfoLink" class="pkt-footer__link">
                <pkt-icon class="pkt-footer__link-icon" name="chevron-right"></pkt-icon>
                Personvern og informasjonskapsler
              </a>
            </li>
            <li class="pkt-footer__list-item">
              <a :href="tilgjengelighetLink" class="pkt-footer__link">
                <pkt-icon class="pkt-footer__link-icon" name="chevron-right"></pkt-icon>
                Tilgjengelighet
              </a>
            </li>
          </ul>
        </div>
      </div>
      <template v-if="socialLinks">
        <div class="pkt-footer__social" aria-label="standard lenker">
          <template v-for="(link, index) in socialLinks">
            <div v-if="link.language" :key="`language-${index}`" class="pkt-footer__social-language">
              <a
                :href="link.href"
                :aria-label="`til ${link.language} versjon av nettsiden`"
                :target="link.openInNewTab ? '_blank' : '_self'"
                :rel="link.openInNewTab ? 'noopener noreferrer' : null"
                >{{ link.language }}</a
              >
            </div>
          </template>
          <div class="pkt-footer__social-icons">
            <template v-for="(link, index) in socialLinks">
              <a
                :key="`sociallinks-${index}`"
                :href="link.href"
                :aria-label="`til ${link.iconName}`"
                :target="link.openInNewTab ? '_blank' : '_self'"
                :rel="link.openInNewTab ? 'noopener noreferrer' : null"
                class="pkt-footer__social-icon-link"
                v-if="link.iconName"
              >
                <pkt-icon class="pkt-footer__social-icon" :name="link.iconName"></pkt-icon>
              </a>
            </template>
          </div>
        </div>
      </template>
    </div>
  </footer>
</template>

<script>
import PktIcon from '../icon/Icon.vue'

export default {
  name: 'PktFooter',
  components: {
    PktIcon,
  },
  props: {
    columnOne: {
      type: Object,
      required: true,
      validator: (value) => {
        return (
          'title' in value &&
          (!('links' in value) ||
            (Array.isArray(value.links) && value.links.every((link) => 'href' in link && 'text' in link)))
        )
      },
    },
    columnTwo: {
      type: Object,
      required: true,
      validator: (value) => {
        return (
          'title' in value &&
          (!('links' in value) ||
            (Array.isArray(value.links) && value.links.every((link) => 'href' in link && 'text' in link)))
        )
      },
    },
    socialLinks: {
      type: Array,
      description: 'Array of social media and language links for the footer',
      validator: (value) => {
        return value.every((link) => {
          if (typeof link === 'object') {
            const hasHref = typeof link.href === 'string'
            const hasIconName = typeof link.iconName === 'string'
            const hasLanguage = typeof link.language === 'string'
            return hasHref && (hasIconName || hasLanguage)
          }
          return false
        })
      },
      required: false,
    },
    personvernOgInfoLink: {
      type: String,
      default: 'https://www.oslo.kommune.no/personvern-og-informasjonskapsler/',
      required: false,
    },
    tilgjengelighetLink: {
      type: String,
      default: 'https://www.oslo.kommune.no/tilgjengelighet/',
      required: false,
    },
  },
}
</script>

// packages/react/src/components/footer/Footer.tsx
import React from 'react'

import { PktIcon } from '../icon/Icon'

interface Link {
  href: string
  text: string
  external?: boolean
  openInNewTab?: boolean
}

interface Column {
  title: string
  links?: Link[]
  text?: string
}

interface SocialLink {
  href: string
  iconName?: string
  language?: string
  openInNewTab?: boolean
}

export interface IPktFooter extends React.HTMLAttributes<HTMLDivElement> {
  columnOne: Column
  columnTwo: Column
  socialLinks?: SocialLink[]
  personvernOgInfoLink?: string
  tilgjengelighetLink?: string
}

export const PktFooter: React.FC<IPktFooter> = ({ columnOne, columnTwo, socialLinks, className, personvernOgInfoLink = "https://www.oslo.kommune.no/personvern-og-informasjonskapsler/", tilgjengelighetLink = "https://www.oslo.kommune.no/tilgjengelighet/"
}) => {
  const classNames = [className, 'pkt-footer'].filter(Boolean).join(' ')
  return (
    <footer className={classNames} data-mode="dark">
      <div className="pkt-footer__container">
        <div className="pkt-grid pkt-grid--rowgap-size-32 pkt-grid--gap-size-16">
          <div className="pkt-footer__column pkt-cell pkt-cell--span12 pkt-cell--span4-laptop-up">
            <h2 className="pkt-footer__title">{columnOne.title}</h2>
            <ul className="pkt-footer__list">
              {columnOne.text && <li className="pkt-footer__text">{columnOne.text}</li>}
              {columnOne.links?.map((link, index) => (
                <li className="pkt-footer__list-item" key={`links-${index}`}>
                  <a
                    className={`pkt-footer__link ${link.external ? 'pkt-link--external' : ''}`}
                    href={link.href}
                    target={link.openInNewTab ? '_blank' : '_self'}
                    rel={link.openInNewTab ? 'noopener noreferrer' : undefined}
                  >
                    <PktIcon className="pkt-footer__link-icon" name="chevron-right" />
                    {link.text}
                  </a>
                </li>
              ))}
            </ul>
          </div>
          <div className="pkt-footer__column pkt-cell pkt-cell--span12 pkt-cell--span4-laptop-up">
            <h2 className="pkt-footer__title">{columnTwo.title}</h2>
            <ul className="pkt-footer__list">
              {columnTwo.text && <li className="pkt-footer__text">{columnTwo.text}</li>}
              {columnTwo.links?.map((link, index) => (
                <li className="pkt-footer__list-item" key={`links-${index}`}>
                  <a
                    className={`pkt-footer__link ${link.external ? 'pkt-link--external' : ''}`}
                    href={link.href}
                    target={link.openInNewTab ? '_blank' : '_self'}
                    rel={link.openInNewTab ? 'noopener noreferrer' : undefined}
                  >
                    <PktIcon className="pkt-footer__link-icon" name="chevron-right" />
                    {link.text}
                  </a>
                </li>
              ))}
            </ul>
          </div>
          <div className="pkt-footer__column pkt-cell pkt-cell--span12 pkt-cell--span4-laptop-up">
            <h2 className="pkt-footer__title">Om nettstedet</h2>
            <ul className="pkt-footer__list">
              <li className="pkt-footer__list-item">
                <a
                  className="pkt-footer__link"
                  href={personvernOgInfoLink}
                >
                  <PktIcon className="pkt-footer__link-icon" name="chevron-right" />
                  Personvern og informasjonskapsler
                </a>
              </li>
              <li className="pkt-footer__list-item">
                <a className="pkt-footer__link" href={tilgjengelighetLink}>
                  <PktIcon className="pkt-footer__link-icon" name="chevron-right" />
                  Tilgjengelighet
                </a>
              </li>
            </ul>
          </div>
        </div>
        {socialLinks && (
          <div className="pkt-footer__social" aria-label="standard lenker">
            <div className="pkt-footer__social-languages">
              {socialLinks
                .filter((link) => link.language)
                .map((link, index) => (
                  <div
                    key={`sociallinks-language-${index}`}
                    className="pkt-footer__social-language"
                  >
                    <a
                      href={link.href}
                      aria-label={`til ${link.language} versjon av nettsiden`}
                      target={link.openInNewTab ? '_blank' : '_self'}
                      rel={link.openInNewTab ? 'noopener noreferrer' : undefined}
                    >
                      {link.language}
                    </a>
                  </div>
                ))}
            </div>
            <div className="pkt-footer__social-icons">
              {socialLinks
                .filter((link) => link.iconName)
                .map((link, index) => (
                  <React.Fragment key={`sociallinks-${index}`}>
                    <a
                      href={link.href}
                      aria-label={`til ${link.iconName}`}
                      className="pkt-footer__social-icon-link"
                      target={link.openInNewTab ? '_blank' : '_self'}
                      rel={link.openInNewTab ? 'noopener noreferrer' : undefined}
                    >
                      <PktIcon className="pkt-footer__social-icon" name={link.iconName} />
                    </a>
                  </React.Fragment>
                ))}
            </div>
          </div>
        )}
      </div>
    </footer>
  )
}
